version: '3'
services:
  vueapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - vueapp-network

networks:
  vueapp-network:
    driver: bridge
